Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/deche-9hFjX_BT-py3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/deche-9hFjX_BT-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/deche-9hFjX_BT-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.cache/pypoetry/virtualenvs/deche-9hFjX_BT-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/deche-9hFjX_BT-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/deche-9hFjX_BT-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/deche-9hFjX_BT-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from deche import Cache

cache = Cache(fs_protocol="memory")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdeche[39;00m [38;5;28;01mimport[39;00m Cache
[1;32m      3[0m cache [38;5;241m=[39m Cache(fs_protocol[38;5;241m=[39m[38;5;124m"[39m[38;5;124mmemory[39m[38;5;124m"[39m)

File [0;32m~/work/deche/deche/deche/__init__.py:10[0m, in [0;36m<module>[0;34m[0m
[1;32m      6[0m __version__ [38;5;241m=[39m version([38;5;18m__name__[39m)
[1;32m      8[0m config [38;5;241m=[39m Config([38;5;124m"[39m[38;5;124mdeche[39m[38;5;124m"[39m)
[0;32m---> 10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdeche[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

File [0;32m~/work/deche/deche/deche/core.py:18[0m, in [0;36m<module>[0;34m[0m
[1;32m     15[0m [38;5;28;01mfrom[39;00m [38;5;21;01mfsspec[39;00m [38;5;28;01mimport[39;00m filesystem
[1;32m     17[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdeche[39;00m [38;5;28;01mimport[39;00m config
[0;32m---> 18[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdeche[39;00m[38;5;21;01m.[39;00m[38;5;21;01menums[39;00m [38;5;28;01mimport[39;00m CacheVersion
[1;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdeche[39;00m[38;5;21;01m.[39;00m[38;5;21;01minspection[39;00m [38;5;28;01mimport[39;00m args_kwargs_to_kwargs
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdeche[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutil[39;00m [38;5;28;01mimport[39;00m ensure_path

[0;31mModuleNotFoundError[0m: No module named 'deche.enums'
ModuleNotFoundError: No module named 'deche.enums'

